# Generated by Django 4.2.20 on 2025-04-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
