# Generated by Django 4.2.20 on 2025-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_appointments', '0002_alter_appointments_date_alter_appointments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
