# Generated by Django 4.2.20 on 2025-04-29 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_patients', '0002_alter_patient_age_alter_patient_gender'),
        ('manage_appointments', '0003_alter_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_patients.patient'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('available', 'متاح'), ('booked', 'محجوز')], default='available', max_length=10),
        ),
    ]
