# Generated by Django 4.2.20 on 2025-04-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coughSound', models.FileField(upload_to='cough_sounds/')),
                ('analysisResult', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_patients.patient')),
            ],
        ),
    ]
