# Generated by Django 4.2.20 on 2025-04-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='coughSound',
            field=models.FileField(blank=True, null=True, upload_to='cough_sounds/'),
        ),
    ]
